### ISSUE TITLE
simulator error in zalo studio

### ISSUE THREAD

**Issue by dattrq** [Zalo-MiniApp/zaui-menu#2]
- Chạy source trên zalo studio 
Error: Build failed with 1 error:
error: Could not resolve "d:\\project\\zalo_mini_app\\zaui-menu\\vite.config.js"

sửa tên file  vite.config.mts --> vite.config.ts lỗi không hiển thị nhưng giao diện simulator trắng trơn

- Deploy development thì báo lỗi 
Error building project
Missing "./preload-helper" export in "vite" package

**Comment by mister-teddy** [comment]
Template này dùng Vite 5.x, nên bạn phải dùng [Extension](https://mini.zalo.me/devtools) chứ không dùng Studio được nhé.
